package com.jsonyao.shardingjdbc.model;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.order_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.product_name
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.num
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.user_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.id
     *
     * @return the value of t_order_item_1.id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.id
     *
     * @param id the value for t_order_item_1.id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.order_id
     *
     * @return the value of t_order_item_1.order_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.order_id
     *
     * @param orderId the value for t_order_item_1.order_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.product_name
     *
     * @return the value of t_order_item_1.product_name
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.product_name
     *
     * @param productName the value for t_order_item_1.product_name
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.num
     *
     * @return the value of t_order_item_1.num
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.num
     *
     * @param num the value for t_order_item_1.num
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.user_id
     *
     * @return the value of t_order_item_1.user_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.user_id
     *
     * @param userId the value for t_order_item_1.user_id
     *
     * @mbg.generated Sun Feb 14 19:28:33 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}