package com.jsonyao.shardingjdbc.dao;

import com.jsonyao.shardingjdbc.model.Area;
import com.jsonyao.shardingjdbc.model.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    long countByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    int deleteByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    List<Area> selectByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Sun Feb 14 12:41:26 CST 2021
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);
}