package com.jsonyao.shardingjdbc.dao;

import com.jsonyao.shardingjdbc.model.OrderItem;
import com.jsonyao.shardingjdbc.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sun Feb 14 13:11:40 CST 2021
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);
}